### ISSUE TITLE
NewWeakGlobalRef JNI function throws exception when passed null parameter

### ISSUE THREAD

**Issue by Boris-Rasin** [corretto/corretto-17#145] opened 2023-08-07 08:19 UTC
### Describe the bug

According to JNI specification, NewWeakGlobalRef function should return null when passed null parameter. Corretto JVM implementation throws exception instead.

### To Reproduce

```c++
void test()
{
	jthrowable e1 = env->ExceptionOccurred();
	env->NewWeakGlobalRef(NULL);
	jthrowable e2 = env->ExceptionOccurred();
}
```

### Expected behavior

No JVM exception should be thrown, e2 var should be zero.

### Platform information
    OS: macOS
    openjdk 17.0.5 2022-10-18 LTS
    OpenJDK Runtime Environment Corretto-17.0.5.8.1 (build 17.0.5+8-LTS)
    OpenJDK 64-Bit Server VM Corretto-17.0.5.8.1 (build 17.0.5+8-LTS, mixed mode, sharing)

**Comment by olivergillespie** [comment] 2023-08-07 09:57
Thanks for reporting. I can confirm this behaviour on Linux for Corretto 17, OpenJDK 17 and OpenJDK tip/22. It does not show on JDK 8 or 11. From a quick look at the code, I think it was introduced by https://bugs.openjdk.org/browse/JDK-8194309, which seems to forget the possibility of a 'valid' null return value [here](https://github.com/openjdk/jdk/blob/dc01604756c22889412f9f25b534488180327317/src/hotspot/share/prims/jni.cpp#L2879-L2881).

Since this is not specific to Corretto, I will report it upstream to OpenJDK.

**Comment by olivergillespie** [comment] 2023-08-07 10:22
I've created https://bugs.openjdk.org/browse/JDK-8313874. I will close this issue since it will be tracked there.
Typically, it will be fixed in OpenJDK tip, and then hopefully backported to OpenJDK 17, at which point we'll pick it up in the next Corretto 17 release. I assume this is not blocking you, since you can work around the issue by inserting a null check yourself before calling `NewWeakGlobalRef`.

Thanks for reporting :)

**Closed as completed by olivergillespie** 2023-08-07 10:22 UTC
