### ISSUE TITLE
NullPointerException in java.util.Spliterator.getExactSizeIfKnown(): "this" is null

### ISSUE THREAD

**Issue by mrjv** [corretto/corretto-17#130] opened 2023-05-22 10:45 UTC
I have raised this in an internal AWS support ticket where I was encouraged to also create a ticket here.

I'm running a Java AWS Lambda function using a custom Amazon Corretto 17 Docker runtime. During execution I got an unexpected NullPointerException in `java.util.Spliterator.estimateSize()` because `"this" is null`. The characteristics of the exception indicates that this issue is related to the runtime or JDK rather than the application code.

### Describe the bug
The failing invocation resulted in the following stack trace:
```
java.lang.NullPointerException: Cannot invoke "java.util.Spliterator.estimateSize()" because "this" is null
at java.base/java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:414) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:508) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[na:na]
at java.base/java.util.stream.ReferencePipeline.min(ReferencePipeline.java:703) ~[na:na]
at org.company.name.SomeClass1.someMethod1(SomeClass1.java:50) ~[lambda1.jar:na]
...
at org.company.name.SomeClass2.someMethod2(SomeClass2.java:82) ~[lambda1.jar:na]
at org.company.name.SomeClass3.lambda$someMethod3$1(SomeClass3.java:61) ~[lambda1.jar:na]
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960) ~[na:na]
at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934) ~[na:na]
at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[na:na]
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
```

The code generating the error is calling `java.util.stream.Stream#min`:
```

    private static final List<SomeClass3> LIST_1 = Arrays.asList( // java.util.Arrays.ArrayList
           new SomeClass3(1.0, 1.0), <6 more entries>, new SomeClass3(POSITIVE_INFINITY, 10.0));

    private static final List<SomeClass3> LIST_2 = Arrays.asList( // java.util.Arrays.ArrayList
           new SomeClass3(1.0, 1.0), <4 more entries>, new SomeClass3(POSITIVE_INFINITY, 10.0));

    public double someMethod1(double value1, double value2) {

        List<SomeClass3> someClass3StaticConstantList;
        if (someCondition(value2)) {
            someClass3StaticConstantList = LIST_1;
        } else {
            someClass3StaticConstantList = LIST_2;
        }

        SomeClass3 object = someClass3StaticConstantList.stream() // 6 or 8 elements
            .filter(l -> someFilter(l, value1, value2))
            .min(Comparator.comparing(SomeClass3::getDouble)) // SomeClass1.java:50, getDouble returns primitive double
            .orElse(DEFAULT_OBJECT);

        return object.getDouble();
    }
```

`someMethod1` is invoked by a parallel stream:
```
    
    Map<String, ResultClass> calculatedResults = someArrayList.stream() // 920 elements
        .parallel()
        .filter(item -> someFilter(item))
        .map(item -> Maps.immutableEntry(
            item.getId(),
            someMethod2(item))) // SomeClass3.java:61, Method that invokes someMethod1
        .filter(entry -> entry.getValue() != null)
        .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue)); // SomeClass3.java:63
```

### To Reproduce
Unable to reproduce. Retriggering the same AWS Lambda function with the same input resulted in no error.

### Expected behavior
No NullPointerException should be thrown by `java.util.Spliterator.getExactSizeIfKnown()`. "this" should never be null.

### Platform information
```
  Lambda Function Memory: 10240 MB
  Lambda Function Base Image: amazoncorretto:17.0.6-al2 
  Lambda Function Java Version: openjdk 17.0.6 2023-01-17 LTS OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)
```

**Comment by olivergillespie** [comment] 2023-08-07 16:26
Thanks for reporting, sorry for the delay. That's interesting and surprising behaviour, I agree. I will try a few ideas to reproduce it, but if we can't reproduce it we'll not have much hope to diagnose and fix it. Did you see the same issue ever again?

**Comment by omkarlenka** [comment] 2023-08-13 18:17
Interesting!! @mrjv Could you mention if the issue happened ever again?

**Comment by mrjv** [comment] 2023-08-14 03:37
@olivergillespie @omkarlenka 
I haven't seen this issue happening again and still haven't been able to reproduce it unfortunately.

This is the first time I have seen "this" being null in Java. Any ideas to what kind of issue that could cause this type of behaviour? JDK issue?

**Comment by olivergillespie** [comment] 2023-08-14 09:00
Thanks. I tried a few things to reproduce it locally but failed. I think it would have to be a JDK bug, like for example a JIT compiler issue. I'll close it for now since it's not causing any issues at the moment, and we don't know how to reproduce it. Feel free to re-open if you see it again.

**Closed as not planned by olivergillespie** 2023-08-14 09:00 UTC
