### ISSUE TITLE
Support for release Alpine aarch64 packages

### ISSUE THREAD

**Issue by janario** [corretto/corretto-17#96] opened 2022-10-06 08:12 UTC
As reported at https://github.com/corretto/corretto-docker/issues/46

It seems that no packages for Alpine(aarch64) are released. As I see a step to enable this would to include in the release process such step to publish the alpine package. Only then docker images would be possible.

Not sure in which project the release and publish is addressed but it seems to me that here would be a good start.

### Is your feature request related to a problem?

During the release/publish process we would require a new step for publishing aarch64 for alpine `https://apk.corretto.aws`

### Describe a solution you would like

Include in the release/publish steps a new package for alpine with aarch64 for `https://apk.corretto.aws`

### Describe alternatives you have considered
Please provide a clear and concise description
of any alternative solutions or features you have considered.

**Comment by lutkerd** [comment] 2022-10-06 16:00
Duplicate of https://github.com/corretto/corretto-docker/issues/46

**Closed as completed by lutkerd** 2022-10-06 16:00 UTC
