### ISSUE TITLE
TarBall for mac is corrupt

### ISSUE THREAD

**Issue by mikebell90** [corretto/corretto-17#14] opened 2021-09-17 20:30 UTC
Download tar ball
tar xvf it
Go to Contents/Home/bin
./java 
Popup appears with corrupt.

Doing the same with pkgutil and pkg appears to work

**Comment by danlemmond** [comment] 2021-09-17 20:34
Attempting to reproduce this on my machine, standby.

**Comment by danlemmond** [comment] 2021-09-17 20:39
```
$ tar xvf amazon-corretto-17.0.0.35.2-macosx-x64.tar.gz
<unzip>
$ cd amazon-corretto-17.jdk/Contents/Home/bin
$ ./java
<usage output>
$ ./java --version                                                                
openjdk 17 2021-09-14 LTS
OpenJDK Runtime Environment Corretto-17.0.0.35.2 (build 17+35-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.0.35.2 (build 17+35-LTS, mixed mode, sharing)
```

This appears normal on my end. Are you able to run a `./java --version`? Which tar.gz do you have? Where did you download it from?

**Comment by mikebell90** [comment] 2021-09-17 20:46
I downloaded it from releases. It untarbslls fine and fails running Java bin

unmentioned but thought to be irrelevant : accidentally downloaded arm version first and got another error of course . Deleted all of that though - this tar all is marked x64

**Comment by mikebell90** [comment] 2021-09-17 20:48
amazon-corretto-17.0.0.35.2-macosx-x64.tar.gz
  187506829 Sep 17 13:18 amazon-corretto-17.0.0.35.2-macosx-x64.tar.gz
shasum amazon-corretto-17.0.0.35.2-macosx-x64.tar.gz
d6e28176355b92c1c027be29ca2f92377658bdc2  amazon-corretto-17.0.0.35.2-macosx-x64.tar.gz

**Comment by mikebell90** [comment] 2021-09-17 20:49
)mbell ~/Downloads/amazon-corretto-17.jdk/Contents/Home/bin $ $ pwd
/Users/mbell/Downloads/amazon-corretto-17.jdk/Contents/Home/bin

**Comment by mikebell90** [comment] 2021-09-17 20:50
![image](https://user-images.githubusercontent.com/780301/133852054-de4bf434-a86e-4bbd-af60-e8aaee1ac4c7.png)

**Comment by mikebell90** [comment] 2021-09-17 20:53
contrast with the package version (pkgutil -expand and then find Payload, rename to payload.tar.gz
mbell ~/java/testing/d/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/bin $ $ ./java -version
openjdk version "17" 2021-09-14 LTS
OpenJDK Runtime Environment Corretto-17.0.0.35.2 (build 17+35-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.0.35.2 (build 17+35-LTS, mixed mode, sharing)

mbell ~/java/testing/d $ $ shasum Payload.tar.gz 
2d52180cc02577eb0bd84167ce7b486b152fb0ff  Payload.tar.gz
(it's wrapped slightly differently so I doubt that matters

**Comment by danlemmond** [comment] 2021-09-17 20:56
Hmm, okay - my `shasum` returns the same response, so it looks like we have the same `tar.gz`. I'm going to try downloading it with Chrome to see if that's throwing it for a loop somehow? In the meantime, can you run a `tar --version` and post that here? We've had some issues with BSD tar in the past, might be contributing.

**Comment by mikebell90** [comment] 2021-09-17 20:56
Verified md5 of pkg and tar.gz are correct:
mbell ~/Downloads $ $ md5 amazon-corretto-17.0.0.35.2-macosx-x64.tar.gz
MD5 (amazon-corretto-17.0.0.35.2-macosx-x64.tar.gz) = 95a51b65b02b59ef59276fac495fc72a

**Comment by mikebell90** [comment] 2021-09-17 20:59
mbell ~/Downloads $ $ tar --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6

**Comment by danlemmond** [comment] 2021-09-17 21:01
Okay this is a much newer version of bsdtar than what I have. Let me try updating my bsdtar and see if that causes the failure.

**Comment by mikebell90** [comment] 2021-09-17 21:01
yup gtar works. But unless this also got hooked to my gui - that also failed. So it is definitely bsdtar. 
Nice to "slack with you" ;)

**Comment by mikebell90** [comment] 2021-09-17 21:04
Anyway the current workaround is to brew install gnu-tar, and use gtar, rather than tar or gui

then just gtar xcf corretto.tar.gz

**Comment by mikebell90** [comment] 2021-09-17 21:06
fwiw docker also generally has needed this when buildkit=true. Sigh.

**Comment by mikebell90** [comment] 2021-09-17 21:07
Tested corretto 11 previous tarball and that worked fine.

**Comment by mikebell90** [comment] 2021-09-17 21:13
I take that back - corretto 11 did fail. So sometime in the last couple months the tar on my box became unhappy ;)

gtar works as a workaround, so I'm not sure what more can be done.

**Comment by danlemmond** [comment] 2021-09-17 21:15
Which version of MacOS are you running? I grabbed and built `bsdtar 3.3.2` and it continues to work on my machine, so my best guess now is a security change.

**Comment by mikebell90** [comment] 2021-09-17 21:22
big sur (11.4)

**Comment by danlemmond** [comment] 2021-09-17 21:25
Gotcha, still on Mojave here so it could very well be a change between the two Mac OS versions.

If you want to verify the binary is from us:
```
codesign -dvvv amazon-corretto-17.jdk/Contents/Home/bin/java
```

Sounds like gtar worked though, hope you enjoy Corretto 17!

**Comment by danlemmond** [comment] 2021-09-17 21:37
Closing this, please re-open if you have any further questions. :)

**Closed as completed by danlemmond** 2021-09-17 21:37 UTC

**Comment by lutkerd** [comment] 2021-09-20 16:37
We had some additional discussion on this internally and macOS can block the tarball when the file is downloaded by the user via Apple’s tools or browsers including Chrome and Firefox. It will get “quarantine” bit and by default it will not be executed.
The cat, gtar are just workarounds, it is also possible to reset that bit with `sudo xattr -r -d com.apple.quarantine /path/to/MyApp.app`. There is more information [here](https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/) and [here](https://gist.github.com/coisme/f89b886ebc508a64fae9b5e2bafb27b5)

**Comment by mikebell90** [comment] 2021-09-20 16:50
Are they relevant @lutkerd if downloaded via mac chrome?

**Comment by lutkerd** [comment] 2021-09-20 16:56
Yes, the major browsers do set the bit, I've updated the comment.

**Comment by mikebell90** [comment] 2021-09-20 16:58
Thanks. It's a bit weird that I've regularly downloaded corretto 11 for years and until recently never ran into that. But...security changes of course ;)

**Comment by mikebell90** [comment] 2021-09-20 16:59
Note that the popup wasn't that "can't open because wasn't verified", which usually you can fix at security panel. This was "it's corrupt", and there was no security exception option
